### ISSUE TITLE
github workflow => line 1: ./setup.sh: No such file or directory

### ISSUE THREAD

**Issue by cmoulliard** [k8s-crafts/podman-cli-action#3]
## Issue

When we use your github action in a flow, then github reports such an error

```
name: Podman cli

on:
  workflow_dispatch:

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Emulate Docker CLI with Podman
        uses: k8s-crafts/podman-cli-action@v1
        #with:
        #  podman_api: true

      - name: Test podman cli
        run: |
          echo $DOCKER_HOST
          podman -v
```

![Screenshot 2024-09-30 at 15 55 50](https://github.com/user-attachments/assets/a5d394d1-7223-4a1b-aa4e-c40d4944a703)
